### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sahal-mulki**
I made README.md a bit better

### CODE REVIEW

**Comment by bacloud14** [comment]
thanks ! I would like "A lot" by the way :)

**Comment by sahal-mulki** [comment]
Ok

**Comment by sahal-mulki** [comment]
So will you merge it and then make Alot, A lot?

**Comment by bacloud14** [comment]
You can update the pull request, it is an exercise for you 😉

**Comment by sahal-mulki** [comment]
And..... I'm done

**Review by bacloud14 — APPROVED** [review]
thanks ! !

**Pull request merged**
